version : "3"

services:
  web:
    container_name: teyou-app
    image: teyou-app
    build: .
    #command: nodemon --exec babel-node --debug=5858 --nolazy src/index.js
    command: npm run serve:docker
    volumes:
      - .:/app
      - ./logs:/app/logs
    ports:
      - "3000:3000"
      - "5858:5858"